include: mujoco_tracking_grand_s_chicane_l234.yaml

experiment:
  name: mujoco_tracking_grand_s_chicane_w4p0d_l239

task:
  corridor_half_width: 1.00
  corridor_half_width_profile:
    - [0.00, 1.00]
    - [1.00, 1.00]
